# Generated by Django 4.1.7 on 2023-04-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saith_API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='token',
            field=models.CharField(max_length=254),
        ),
    ]
