# Generated by Django 4.1.7 on 2023-04-03 19:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('saith_API', '0003_alter_sessions_id_alter_users_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('certificate', models.BinaryField()),
                ('password', models.CharField(max_length=254)),
                ('expiration', models.DateTimeField()),
                ('document', models.CharField(max_length=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'default_related_name': 'certificate',
            },
        ),
        migrations.AddField(
            model_name='sessions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserCertificate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saith_API.certificate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saith_API.users')),
            ],
            options={
                'default_related_name': 'user_certificate',
            },
        ),
    ]
