# Generated by Django 4.1.7 on 2023-04-03 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saith_API', '0004_certificate_sessions_created_at_usercertificate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCertificate',
            new_name='User_Certificate',
        ),
    ]
