# Generated by Django 4.1.7 on 2023-04-04 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saith_API', '0005_rename_usercertificate_user_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document', models.CharField(max_length=14)),
                ('last_ncu', models.CharField(max_length=254)),
            ],
            options={
                'default_related_name': 'document',
            },
        ),
        migrations.CreateModel(
            name='NFE',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ncu', models.CharField(max_length=254)),
                ('seller', models.CharField(max_length=254)),
                ('number', models.CharField(max_length=254)),
                ('value_nfe', models.FloatField()),
                ('date', models.DateTimeField()),
                ('has_nfe_complete', models.BooleanField(default=False)),
                ('nfe', models.BinaryField()),
                ('answered', models.BooleanField(default=False)),
                ('answer', models.CharField(max_length=254)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saith_API.document')),
            ],
            options={
                'default_related_name': 'nfe',
            },
        ),
        migrations.CreateModel(
            name='User_Certificate_Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'default_related_name': 'user_certificate_document',
            },
        ),
        migrations.CreateModel(
            name='User_Document_Valid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_valid', models.BooleanField(default=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saith_API.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saith_API.users')),
            ],
            options={
                'default_related_name': 'user_document_valid',
            },
        ),
        migrations.AddField(
            model_name='certificate',
            name='code',
            field=models.CharField(default=31548651564858, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='User_Certificate',
        ),
        migrations.AddField(
            model_name='user_certificate_document',
            name='certificate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saith_API.certificate'),
        ),
        migrations.AddField(
            model_name='user_certificate_document',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saith_API.document'),
        ),
        migrations.AddField(
            model_name='user_certificate_document',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saith_API.users'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saith_API.document'),
        ),
    ]
