# Generated by Django 4.1.7 on 2023-04-12 19:00

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saith_API', '0006_document_nfe_user_certificate_document_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nfe',
            old_name='ncu',
            new_name='nsu',
        ),
        migrations.AddField(
            model_name='nfe',
            name='document_seller',
            field=models.CharField(default=31548651564858, max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nfe',
            name='operation_science',
            field=models.BooleanField(default=False),
        ),
    ]
