# Generated by Django 4.1.7 on 2023-04-13 04:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('saith_API', '0007_rename_ncu_nfe_nsu_nfe_document_seller_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='last_batch',
            field=models.CharField(default='1', max_length=254),
        ),
        migrations.AddField(
            model_name='document',
            name='last_requisition_nfe',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='last_ncu',
            field=models.CharField(default='0', max_length=254),
        ),
    ]
