# Generated by Django 4.1.7 on 2023-04-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saith_API', '0008_document_last_batch_document_last_requisition_nfe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='uf',
            field=models.CharField(default=33, max_length=2),
            preserve_default=False,
        ),
    ]
