# Generated by Django 4.1.7 on 2023-04-13 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saith_API', '0009_certificate_uf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='last_requisition_nfe',
            new_name='last_request_nfe',
        ),
    ]
