# Generated by Django 4.1.7 on 2023-04-14 20:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('saith_API', '0012_rename_document_document_document_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(default='CNPJ', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(default='Mercado Raizes ldta', max_length=254),
            preserve_default=False,
        ),
    ]
