# Generated by Django 4.1.7 on 2023-04-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saith_API', '0013_document_document_type_document_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfe',
            name='operation_science_date',
            field=models.DateTimeField(null=True),
        ),
    ]
